# Generated by Django 4.2 on 2026-03-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='expiry_time',
            field=models.CharField(default='4 hours', max_length=100),
            preserve_default=False,
        ),
    ]
