# Generated by Django 4.2 on 2026-05-04 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_collection_status_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='ngo_name',
        ),
        migrations.AddField(
            model_name='collection',
            name='ngo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ngo'),
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='food_images/'),
        ),
        migrations.AddField(
            model_name='eventmanager',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
