# Generated by Django 4.2 on 2026-05-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_donation_event_latitude_event_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('ngo', 'NGO'), ('event_manager', 'Event Manager')], max_length=20),
        ),
    ]
