# Generated by Django 4.2 on 2026-05-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ngo',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
