# Generated by Django 4.2 on 2026-05-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_ngo_latitude_ngo_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
