# Generated by Django 4.2 on 2026-05-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_ngo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='priority_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Pickup Started', 'Pickup Started'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered')], default='Accepted', max_length=50),
        ),
    ]
